---
platform: linux
image: "docker:///java#8"
inputs:
  - name: weather
outputs:
  - name: build
    path: weather/artifacts
run:
  path: "weather/gradlew"
  args: ["buildAndFind", "-pweather"]
params:
  "TERM": "xterm"

